Repository VUnit/vunit, pull requests merged in 2022-05, with the labels that each got.

#825 Updated rivierapro.py as discussed in pull request #621
  vunit/sim_if/rivierapro.py
Labels: Simulator support, Needs testing

#828 ci/push: remove job win-tagged
  .github/workflows/push.yml
Labels: CI

#832 docs/about: fixed typo from "GDHL" to "GHDL"
  docs/_static/VUnit_diagram.png
  docs/_static/vunit.drawio
Labels: Bug, Docs
